services:
  db:
    image: postgres:16  # Use a stable official image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devansh123
      POSTGRES_DB: git_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:devansh123@db:5432/git_db
      SLACK_WEBHOOK: url of slack
      SECRET_KEY: devansh123lamaniya
      SENDERS_EMAIL: devansh.lamaniya@gammaedge.io
      EMAIL_PASSWORD: dtgmrgruajxuofkz
      receivers_email: abahay.shukla@gammaedge.io
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devansh123
      POSTGRES_DB: git_db
    depends_on:
      - db
    volumes:
      - .:/app  

volumes:
  postgres_data:
